name: prestamos
description: "Aplicacion para gestionar prestamos."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  intl: ^0.19.0
  provider: ^6.0.0
  path_provider: ^2.1.5
  open_file: ^3.5.10
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_localization: ^0.2.0
  shared_preferences: ^2.3.3
  connectivity_plus: ^6.1.1
  go_router: ^14.6.2



dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  freezed: ^2.5.7

flutter:
  uses-material-design: true
  generate: true
